datagrids:
    training-user-naming-types-grid:
        source:
            type: orm
            query:
                select:
                    - type.id
                    - type.title
                    - type.format
                from:
                    - { table: Training\Bundle\UserNamingBundle\Entity\UserNamingType, alias: type }
        columns:
            id:
                label: training.usernaming.type.id.label
            title:
                label: training.usernaming.type.title.label
            format:
                label: training.usernaming.type.format.label
            example:
                label: "Example"
            enabled:
                frontend_type: select
                editable: true
                choices:
                    Active: 1
                    Inactive: 0
        properties:
            id: ~
            view_link:
                type: url
                route: training_user_naming_show
                params: [ id ]
            edit_link:
                type: url
                route: training_user_naming_show
                params: [ id ]
            delete_link:
                type: url
                route: training_user_naming_delete
                params: [ id ]
        actions:
            view:
                type: navigate
                label: oro.grid.action.view
                link: view_link
                icon: eye
                rowAction: true
            edit:
                type: navigate
                label: oro.grid.action.edit
                link: edit_link
                icon: edit
                rowAction: true
            delete:
                type: delete
                label: oro.grid.action.delete
                icon: trash
                link: delete_link

    training-user-naming-users-grid:
        source:
            type: orm
            query:
                select:
                    - user.username
                    - user.firstName
                    - user.middleName
                    - user.lastName
                    - user.email
                from:
                    - { table: Oro\Bundle\UserBundle\Entity\User, alias: user }
                where:
                    and:
                        - IDENTITY(user.namingType) = :namingTypeId
            bind_parameters:
                - name: namingTypeId
        columns:
            username:
                label: 'oro.user.username.label'
            firstName:
                label: 'oro.user.first_name.label'
            middleName:
                label: 'oro.user.middle_name.label'
            lastName:
                label: 'oro.user.last_name.label'
            email:
                label: 'oro.user.email.label'


