navigation:
    menu_config:
        items:
            user_naming:
                label: 'training.usernaming.entity_plural_label'
                route: 'training_user_naming_index'
                position: 10
        tree:
            application_menu:
                children:
                    system_tab:
                        children:
                            users_management:
                                children:
                                    user_naming: ~
