<?php

namespace Training\Bundle\UserNamingBundle\Command;

use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Training\Bundle\UserNamingBundle\Integration\Connector\TrainingUserNamingTypeImportConnector;

class TrainingUserNamingIntegrationCommand extends Command
{
    protected static $defaultName = 'training:usernaming:import';

    private TrainingUserNamingTypeImportConnector $connector;

    /**
     * @param TrainingUserNamingTypeImportConnector $connector
     */
    public function setConnector(TrainingUserNamingTypeImportConnector $connector): void
    {
        $this->connector = $connector;
    }

    protected function configure()
    {
        parent::configure(); // TODO: Change the autogenerated stub
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $this->connector->importUserNamingTypes();
        return Command::SUCCESS;
    }

}
