services:
  _defaults:
    autowire: true

  Training\Bundle\UserNamedBundle\Provider\UserNamedProviderDecorator:
    decorates: Oro\Bundle\LocaleBundle\Provider\EntityNameProvider
    arguments:
      - '@Training\Bundle\UserNamedBundle\Provider\UserNamedProviderDecorator.inner'
    tags:
      - { name: oro_entity.name_provider, priority: -60 }

  Training\Bundle\UserNamedBundle\EventListener\UserViewListener:
    tags:
      - { name: kernel.event_listener, event: oro_ui.scroll_data.before.userView, method: onUserView }

  Training\Bundle\UserNamedBundle\Twig\Extension\UserNameExtension:
    tags:
      - { name: twig.extension }

  Oro\Bundle\LocaleBundle\Provider\EntityNameProvider: '@oro_locale.entity_name_provider'
