services:
  _defaults:
    autowire: true
    autoconfigure: true

  Training\Bundle\UserNamingBundle\:
    resource: '../../*'

  Training\Bundle\UserNamingBundle\Provider\UserNamingProviderDecorator:
    decorates: Oro\Bundle\LocaleBundle\Provider\EntityNameProvider
    arguments:
      - '@Training\Bundle\UserNamingBundle\Provider\UserNamingProviderDecorator.inner'
      - '@Training\Bundle\UserNamingBundle\Service\NamingConverterInterface'
    tags:
      - { name: oro_entity.name_provider, priority: -60 }

  Training\Bundle\UserNamingBundle\EventListener\UserViewListener:
    tags:
      - { name: kernel.event_listener, event: oro_ui.scroll_data.before.userView, method: onUserView }

  Training\Bundle\UserNamingBundle\Service\UserNamingFormatterService:
    calls:
      - setContainer: [ '@service_container' ]

  training_user_naming_formatter:
    class: Training\Bundle\UserNamingBundle\Service\NamingConverter

  Training\Bundle\UserNamingBundle\Service\NamingConverterInterface: '@training_user_naming_formatter'

  Training\Bundle\UserNamingBundle\Twig\Extension\UserNamingExtension:
    arguments:
      - '@Training\Bundle\UserNamingBundle\Service\NamingConverterInterface'
    tags:
      - { name: twig.extension }

  Oro\Bundle\LocaleBundle\Provider\EntityNameProvider: '@oro_locale.entity_name_provider'

  training.usernaming.example.format:
    public: true
    class: Training\Bundle\UserNamingBundle\Service\TrainingNamingConverterExample
